// <auto-generated />
using System;
using AnimalShelter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterDbContext))]
    partial class AnimalShelterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("AnimalShelter.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Warszawa",
                            Country = "Polska",
                            PostalCode = "00-001",
                            StreetAddress = "ul. Kwiatowa 1"
                        },
                        new
                        {
                            Id = 2,
                            City = "Kraków",
                            Country = "Polska",
                            PostalCode = "30-002",
                            StreetAddress = "ul. Leśna 5"
                        },
                        new
                        {
                            Id = 3,
                            City = "Poznań",
                            Country = "Polska",
                            PostalCode = "60-003",
                            StreetAddress = "ul. Słoneczna 10"
                        },
                        new
                        {
                            Id = 4,
                            City = "Gdańsk",
                            Country = "Polska",
                            PostalCode = "80-004",
                            StreetAddress = "ul. Morska 7"
                        },
                        new
                        {
                            Id = 5,
                            City = "Zakopane",
                            Country = "Polska",
                            PostalCode = "34-500",
                            StreetAddress = "ul. Górska 15"
                        },
                        new
                        {
                            Id = 6,
                            City = "Wrocław",
                            Country = "Polska",
                            PostalCode = "50-005",
                            StreetAddress = "ul. Spacerowa 20"
                        },
                        new
                        {
                            Id = 7,
                            City = "Lublin",
                            Country = "Polska",
                            PostalCode = "20-006",
                            StreetAddress = "ul. Zielona 3"
                        });
                });

            modelBuilder.Entity("AnimalShelter.Models.Adoption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddressId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AdoptionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("AnimalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("AnimalId");

                    b.ToTable("Adoptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            AdoptionDate = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AnimalId = 1,
                            Email = "jan.kowalski@example.com",
                            FullName = "Jan Kowalski",
                            Notes = "Brak uwag",
                            PhoneNumber = "123456789"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 3,
                            AdoptionDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            AnimalId = 9,
                            Email = "anna.nowak@example.com",
                            FullName = "Anna Nowak",
                            Notes = "Adopcja przebiegła pomyślnie",
                            PhoneNumber = "987654321"
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 5,
                            AdoptionDate = new DateTime(2024, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            AnimalId = 4,
                            Email = "piotr.zielinski@example.com",
                            FullName = "Piotr Zieliński",
                            Notes = "Nowy dom z ogrodem",
                            PhoneNumber = "555666777"
                        });
                });

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Breed")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsAdopted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Microchip")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 3,
                            Breed = "Mieszaniec",
                            Color = "Czarny",
                            Gender = "Samiec",
                            IsAdopted = true,
                            Location = "Boks 1",
                            Microchip = "1234567890",
                            Name = "Kajtek",
                            Size = "Duży",
                            Species = "Pies"
                        },
                        new
                        {
                            Id = 2,
                            Age = 2,
                            Breed = "Europejski",
                            Color = "Szary",
                            Gender = "Samica",
                            IsAdopted = false,
                            Location = "Boks 2",
                            Microchip = "0987654321",
                            Name = "Luna",
                            Size = "Mały",
                            Species = "Kot"
                        },
                        new
                        {
                            Id = 3,
                            Age = 4,
                            Breed = "Owczarek niemiecki",
                            Color = "Brązowy",
                            Gender = "Samica",
                            IsAdopted = false,
                            Location = "Boks 3",
                            Microchip = "2233445566",
                            Name = "Sara",
                            Size = "Duży",
                            Species = "Pies"
                        },
                        new
                        {
                            Id = 4,
                            Age = 2,
                            Breed = "Beagle",
                            Color = "Tricolor",
                            Gender = "Samiec",
                            IsAdopted = true,
                            Location = "Boks 4",
                            Microchip = "3344556677",
                            Name = "Benio",
                            Size = "Średni",
                            Species = "Pies"
                        },
                        new
                        {
                            Id = 5,
                            Age = 5,
                            Breed = "Mieszaniec",
                            Color = "Złoty",
                            Gender = "Samica",
                            IsAdopted = false,
                            Location = "Boks 5",
                            Microchip = "4455667788",
                            Name = "Mila",
                            Size = "Duży",
                            Species = "Pies"
                        },
                        new
                        {
                            Id = 6,
                            Age = 6,
                            Breed = "Bulldog",
                            Color = "Biały",
                            Gender = "Samiec",
                            IsAdopted = false,
                            Location = "Boks 6",
                            Microchip = "5566778899",
                            Name = "Gucio",
                            Size = "Średni",
                            Species = "Pies"
                        },
                        new
                        {
                            Id = 7,
                            Age = 3,
                            Breed = "Mieszaniec",
                            Color = "Srebrny",
                            Gender = "Samica",
                            IsAdopted = false,
                            Location = "Boks 7",
                            Microchip = "6677889900",
                            Name = "Tosia",
                            Size = "Mały",
                            Species = "Pies"
                        },
                        new
                        {
                            Id = 8,
                            Age = 1,
                            Breed = "Mieszaniec",
                            Color = "Brązowy",
                            Gender = "Samiec",
                            IsAdopted = false,
                            Location = "Boks 8",
                            Microchip = "7788990011",
                            Name = "Felek",
                            Size = "Mały",
                            Species = "Pies"
                        },
                        new
                        {
                            Id = 9,
                            Age = 5,
                            Breed = "Syjamski",
                            Color = "Biały",
                            Gender = "Samiec",
                            IsAdopted = true,
                            Location = "Boks 9",
                            Microchip = "8899001122",
                            Name = "Leo",
                            Size = "Mały",
                            Species = "Kot"
                        },
                        new
                        {
                            Id = 10,
                            Age = 3,
                            Breed = "Mieszaniec",
                            Color = "Biały",
                            Gender = "Samica",
                            IsAdopted = false,
                            Location = "Boks 10",
                            Microchip = "9900112233",
                            Name = "Klara",
                            Size = "Mały",
                            Species = "Kot"
                        },
                        new
                        {
                            Id = 11,
                            Age = 4,
                            Breed = "Maine Coon",
                            Color = "Rudy",
                            Gender = "Samiec",
                            IsAdopted = false,
                            Location = "Boks 11",
                            Microchip = "1011121314",
                            Name = "Rufus",
                            Size = "Duży",
                            Species = "Kot"
                        },
                        new
                        {
                            Id = 12,
                            Age = 2,
                            Breed = "Mieszaniec",
                            Color = "Pręgowany",
                            Gender = "Samica",
                            IsAdopted = false,
                            Location = "Boks 12",
                            Microchip = "1213141516",
                            Name = "Zoe",
                            Size = "Średni",
                            Species = "Kot"
                        },
                        new
                        {
                            Id = 13,
                            Age = 1,
                            Breed = "Sfinks",
                            Color = "Beżowy",
                            Gender = "Samiec",
                            IsAdopted = false,
                            Location = "Boks 13",
                            Microchip = "1314151617",
                            Name = "Neo",
                            Size = "Mały",
                            Species = "Kot"
                        },
                        new
                        {
                            Id = 14,
                            Age = 3,
                            Breed = "Mieszaniec",
                            Color = "Niebieski",
                            Gender = "Samica",
                            IsAdopted = false,
                            Location = "Boks 14",
                            Microchip = "1415161718",
                            Name = "Nina",
                            Size = "Mały",
                            Species = "Kot"
                        },
                        new
                        {
                            Id = 15,
                            Age = 2,
                            Breed = "Mieszaniec",
                            Color = "Czarny",
                            Gender = "Samiec",
                            IsAdopted = false,
                            Location = "Boks 15",
                            Microchip = "1516171819",
                            Name = "Czarek",
                            Size = "Mały",
                            Species = "Kot"
                        },
                        new
                        {
                            Id = 16,
                            Age = 7,
                            Breed = "Labrador",
                            Color = "Czekoladowy",
                            Gender = "Samiec",
                            IsAdopted = false,
                            Location = "Boks 16",
                            Microchip = "1617181920",
                            Name = "Borys",
                            Size = "Duży",
                            Species = "Pies"
                        },
                        new
                        {
                            Id = 17,
                            Age = 2,
                            Breed = "Shih Tzu",
                            Color = "Biały",
                            Gender = "Samica",
                            IsAdopted = true,
                            Location = "Boks 17",
                            Microchip = "1718192021",
                            Name = "Misia",
                            Size = "Mały",
                            Species = "Pies"
                        },
                        new
                        {
                            Id = 18,
                            Age = 4,
                            Breed = "Border Collie",
                            Color = "Czarny",
                            Gender = "Samiec",
                            IsAdopted = false,
                            Location = "Boks 18",
                            Microchip = "1819202122",
                            Name = "Riko",
                            Size = "Średni",
                            Species = "Pies"
                        },
                        new
                        {
                            Id = 19,
                            Age = 3,
                            Breed = "Brytyjski",
                            Color = "Szary",
                            Gender = "Samica",
                            IsAdopted = false,
                            Location = "Boks 19",
                            Microchip = "1920212223",
                            Name = "Bella",
                            Size = "Mały",
                            Species = "Kot"
                        },
                        new
                        {
                            Id = 20,
                            Age = 6,
                            Breed = "Golden Retriever",
                            Color = "Złoty",
                            Gender = "Samiec",
                            IsAdopted = false,
                            Location = "Boks 20",
                            Microchip = "2021222324",
                            Name = "Maks",
                            Size = "Duży",
                            Species = "Pies"
                        },
                        new
                        {
                            Id = 21,
                            Age = 2,
                            Breed = "Perski",
                            Color = "Biały",
                            Gender = "Samica",
                            IsAdopted = false,
                            Location = "Boks 21",
                            Microchip = "2122232425",
                            Name = "Daisy",
                            Size = "Mały",
                            Species = "Kot"
                        },
                        new
                        {
                            Id = 22,
                            Age = 1,
                            Breed = "Jack Russell",
                            Color = "Biały",
                            Gender = "Samiec",
                            IsAdopted = false,
                            Location = "Boks 22",
                            Microchip = "2223242526",
                            Name = "Tobi",
                            Size = "Mały",
                            Species = "Pies"
                        },
                        new
                        {
                            Id = 23,
                            Age = 5,
                            Breed = "Mieszaniec",
                            Color = "Czarny",
                            Gender = "Samica",
                            IsAdopted = true,
                            Location = "Boks 23",
                            Microchip = "2324252627",
                            Name = "Mela",
                            Size = "Mały",
                            Species = "Kot"
                        },
                        new
                        {
                            Id = 24,
                            Age = 3,
                            Breed = "Mieszaniec",
                            Color = "Rudy",
                            Gender = "Samiec",
                            IsAdopted = false,
                            Location = "Boks 24",
                            Microchip = "2425262728",
                            Name = "Simba",
                            Size = "Średni",
                            Species = "Pies"
                        },
                        new
                        {
                            Id = 25,
                            Age = 4,
                            Breed = "Syjamski",
                            Color = "Biały",
                            Gender = "Samica",
                            IsAdopted = false,
                            Location = "Boks 25",
                            Microchip = "2526272829",
                            Name = "Lili",
                            Size = "Mały",
                            Species = "Kot"
                        },
                        new
                        {
                            Id = 26,
                            Age = 2,
                            Breed = "Dalmatyńczyk",
                            Color = "Czarny-biały",
                            Gender = "Samiec",
                            IsAdopted = false,
                            Location = "Boks 26",
                            Microchip = "2627282930",
                            Name = "Oskar",
                            Size = "Duży",
                            Species = "Pies"
                        },
                        new
                        {
                            Id = 27,
                            Age = 3,
                            Breed = "Mieszaniec",
                            Color = "Biały-pręgowany",
                            Gender = "Samica",
                            IsAdopted = false,
                            Location = "Boks 27",
                            Microchip = "2728293031",
                            Name = "Maja",
                            Size = "Mały",
                            Species = "Kot"
                        },
                        new
                        {
                            Id = 28,
                            Age = 5,
                            Breed = "Jamnik",
                            Color = "Brązowy",
                            Gender = "Samica",
                            IsAdopted = false,
                            Location = "Boks 28",
                            Microchip = "2829303132",
                            Name = "Bambi",
                            Size = "Mały",
                            Species = "Pies"
                        },
                        new
                        {
                            Id = 29,
                            Age = 6,
                            Breed = "Mieszaniec",
                            Color = "Czarny",
                            Gender = "Samiec",
                            IsAdopted = false,
                            Location = "Boks 29",
                            Microchip = "2930313233",
                            Name = "Kuba",
                            Size = "Mały",
                            Species = "Kot"
                        },
                        new
                        {
                            Id = 30,
                            Age = 4,
                            Breed = "Sznaucer",
                            Color = "Srebrny",
                            Gender = "Samica",
                            IsAdopted = false,
                            Location = "Boks 30",
                            Microchip = "3031323334",
                            Name = "Pola",
                            Size = "Średni",
                            Species = "Pies"
                        },
                        new
                        {
                            Id = 31,
                            Age = 2,
                            Breed = "Mieszaniec",
                            Color = "Szary",
                            Gender = "Samiec",
                            IsAdopted = false,
                            Location = "Boks 31",
                            Microchip = "3132333435",
                            Name = "Rysio",
                            Size = "Mały",
                            Species = "Kot"
                        },
                        new
                        {
                            Id = 32,
                            Age = 1,
                            Breed = "Mieszaniec",
                            Color = "Biały",
                            Gender = "Samica",
                            IsAdopted = false,
                            Location = "Boks 32",
                            Microchip = "3233343536",
                            Name = "Kira",
                            Size = "Mały",
                            Species = "Pies"
                        },
                        new
                        {
                            Id = 33,
                            Age = 3,
                            Breed = "Mieszaniec",
                            Color = "Pręgowany",
                            Gender = "Samiec",
                            IsAdopted = false,
                            Location = "Boks 33",
                            Microchip = "3334353637",
                            Name = "Miki",
                            Size = "Mały",
                            Species = "Kot"
                        },
                        new
                        {
                            Id = 34,
                            Age = 2,
                            Breed = "Mieszaniec",
                            Color = "Czarny",
                            Gender = "Samica",
                            IsAdopted = false,
                            Location = "Boks 34",
                            Microchip = "3435363738",
                            Name = "Fiona",
                            Size = "Średni",
                            Species = "Pies"
                        },
                        new
                        {
                            Id = 35,
                            Age = 4,
                            Breed = "Mieszaniec",
                            Color = "Szylkret",
                            Gender = "Samica",
                            IsAdopted = false,
                            Location = "Boks 35",
                            Microchip = "3536373839",
                            Name = "Sonia",
                            Size = "Mały",
                            Species = "Kot"
                        },
                        new
                        {
                            Id = 36,
                            Age = 5,
                            Breed = "Owczarek podhalański",
                            Color = "Biały",
                            Gender = "Samiec",
                            IsAdopted = false,
                            Location = "Boks 36",
                            Microchip = "3637383940",
                            Name = "Borys",
                            Size = "Duży",
                            Species = "Pies"
                        },
                        new
                        {
                            Id = 37,
                            Age = 2,
                            Breed = "Mieszaniec",
                            Color = "Czarny",
                            Gender = "Samica",
                            IsAdopted = false,
                            Location = "Boks 37",
                            Microchip = "3738394041",
                            Name = "Marta",
                            Size = "Mały",
                            Species = "Kot"
                        },
                        new
                        {
                            Id = 38,
                            Age = 3,
                            Breed = "Mieszaniec",
                            Color = "Brązowy",
                            Gender = "Samiec",
                            IsAdopted = false,
                            Location = "Boks 38",
                            Microchip = "3839404142",
                            Name = "Tytus",
                            Size = "Średni",
                            Species = "Pies"
                        },
                        new
                        {
                            Id = 39,
                            Age = 1,
                            Breed = "Mieszaniec",
                            Color = "Biały",
                            Gender = "Samica",
                            IsAdopted = false,
                            Location = "Boks 39",
                            Microchip = "3940414243",
                            Name = "Lola",
                            Size = "Mały",
                            Species = "Kot"
                        },
                        new
                        {
                            Id = 40,
                            Age = 2,
                            Breed = "Mieszaniec",
                            Color = "Czarny",
                            Gender = "Samiec",
                            IsAdopted = false,
                            Location = "Boks 40",
                            Microchip = "4041424344",
                            Name = "Bingo",
                            Size = "Duży",
                            Species = "Pies"
                        });
                });

            modelBuilder.Entity("AnimalShelter.Models.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalNotes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("AddressId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Volunteers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdditionalNotes = "Może pracować w weekendy",
                            AddressId = 7,
                            Email = "piotr.zielinski@example.com",
                            FullName = "Piotr Zieliński",
                            PhoneNumber = "555666777"
                        },
                        new
                        {
                            Id = 2,
                            AdditionalNotes = "Dostępna popołudniami",
                            AddressId = 6,
                            Email = "anna.maj@example.com",
                            FullName = "Anna Maj",
                            PhoneNumber = "600700800"
                        },
                        new
                        {
                            Id = 3,
                            AdditionalNotes = "Może pracować tylko w poniedziałki",
                            AddressId = 1,
                            Email = "tomasz.nowak@example.com",
                            FullName = "Tomasz Nowak",
                            PhoneNumber = "601701801"
                        },
                        new
                        {
                            Id = 4,
                            AdditionalNotes = "Lubi pracować ze zwierzętami starszymi",
                            AddressId = 1,
                            Email = "karolina.wisniewska@example.com",
                            FullName = "Karolina Wiśniewska",
                            PhoneNumber = "602702802"
                        },
                        new
                        {
                            Id = 5,
                            AdditionalNotes = "Dostępny w weekendy",
                            AddressId = 2,
                            Email = "marek.lewandowski@example.com",
                            FullName = "Marek Lewandowski",
                            PhoneNumber = "603703803"
                        },
                        new
                        {
                            Id = 6,
                            AdditionalNotes = "Może pomagać przy adopcjach",
                            AddressId = 3,
                            Email = "ewa.kaczmarek@example.com",
                            FullName = "Ewa Kaczmarek",
                            PhoneNumber = "604704804"
                        },
                        new
                        {
                            Id = 7,
                            AdditionalNotes = "Zainteresowany opieką nad psami",
                            AddressId = 4,
                            Email = "grzegorz.lis@example.com",
                            FullName = "Grzegorz Lis",
                            PhoneNumber = "605705805"
                        },
                        new
                        {
                            Id = 8,
                            AdditionalNotes = "Pomoc w organizacji wydarzeń",
                            AddressId = 5,
                            Email = "magdalena.bak@example.com",
                            FullName = "Magdalena Bąk",
                            PhoneNumber = "606706806"
                        });
                });

            modelBuilder.Entity("AnimalShelter.Models.Adoption", b =>
                {
                    b.HasOne("AnimalShelter.Models.Address", "Address")
                        .WithMany("Adoptions")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimalShelter.Models.Animal", "Animal")
                        .WithMany("Adoptions")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("AnimalShelter.Models.Volunteer", b =>
                {
                    b.HasOne("AnimalShelter.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("AnimalShelter.Models.Address", b =>
                {
                    b.Navigation("Adoptions");
                });

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Navigation("Adoptions");
                });
#pragma warning restore 612, 618
        }
    }
}
